name: surfel_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pillow=10.2.0
  - pip=24.2
  - python=3.8.20
  - typing_extensions=4.9.0
  - pip:
    - pytorch==2.4.0+cu118
    - torchaudio==2.4.0+cu118
    - torchvision==0.19.0+cu118
    - ffmpeg-python
    - open3d==0.18.0
    - mediapy==1.1.2
    - lpips==0.1.4
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - submodules/diff-surfel-rasterization
    - submodules/simple-knn
    - plyfile
    - opencv-python